# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Maven@3
  inputs:
    mavenPOMFile: 'pom.xml'
    sqAnalysisEnabled: true
    checkstyleAnalysisEnabled: true
    findbugsAnalysisEnabled: true
    